We will love to get a little sponsorship donations even as little as $20 to build this project to finish...
This Project Sponosred By: SPARS TECHNOLOGIES LIMITED
ALL Contributions goes to: 
Account Name: Spars Technologies Limited
Account Number (USD): 0826287064
Bank Name: Guaranteed Trust Bank
Swift Code: GTBIGB2L
